#!/bin/bash

mainfolder="$(realpath "$1")"
if [ ! -d "$mainfolder" ]; then
	echo -e "Oppps!!!! Forgot to specify folder!"

	exit 1
fi

cd "$mainfolder" || {
	echo "Usage: $(basename "$0") Week folder"
	exit 1
}
mkdir -p "$mainfolder"/all
n=0
tagged=()
for i in *.jpg; do
	if tag "$i" | grep -q '\tGreen'; then
		((n++))
		tagged+=("$i")
	fi
done

testdup=()
for i in "${tagged[@]}"; do
	testdup+=("${i%-*}.jpg")
done
dupe=$(
	IFS=$'\n' sort <<<"${testdup[*]}" | uniq -d
	unset IFS
)
if [[ $dupe ]]; then
	echo "Show $dupe was tagged multiple times!!!! Only select 1"
	exit 1
fi

# if [[ $n != 5 ]]; then
# 	echo "There should be 5 shows tagged... There are only $n"
# 	exit 1
# fi
echo "Thumbnails will be:"
for x in "${tagged[@]}"; do
	echo "${x%-*}.jpg"
done
while true; do
	read -rt 10 -n 1 -p "Do this look correct? (Y/n) " yn
	yn="${yn:=y}"
	case $yn in
	[Yy]*)
		echo "Good! We will continue."
		break
		;;
	[Nn]*)
		echo "Exiting"
		exit 1
		;;
	*) echo "Please answer yes or no." ;;
	esac
done
mv "$mainfolder"/*.jpg "$mainfolder"/all

cd all || exit
for i in "${tagged[@]}"; do
	# if [[ $( tag "$i" | grep '\tGreen' ) ]]; then
	echo "Processing ${i%-*}.jpg"
	cp "$i" ../"${i%-*}.jpg"
	# fi
done
