#!/bin/bash

DEFAULT_APP_PATH="/Applications/Topaz Video AI.app"
APP_PATH=${1:-$DEFAULT_APP_PATH}

APP_FILE="$APP_PATH/Contents/MacOS/login"
LIB_FILE="$(readlink -f "$APP_PATH/Contents/Frameworks/libvideoai.dylib")"

HEX_VALUES_APP=(
  'A3030054'     '55000014'     # Arm64 Redirect to logged in
  '0F8297000000' '660F1F440000' # x86 Skip Not Logging In
  '0F8430060000' 'E93106000000' # x86 Jump to LogIn Success
)

HEX_VALUES_LIB=(
  '62020054200080' '62020054000080' # Arm64 Remove Watermark
  'B0014180'       'B0004180'       # x86 Remove Watermark
)

# Check for required utilities
check_utilities() {
  local utilities=("perl" "codesign")

  for util in "${utilities[@]}"; do
    command -v "$util" >/dev/null 2>&1 || {
      echo >&2 "Error: $util is required but not installed. try running 'xcode-select --install'"
      exit 1
    }
  done
}

hex() {
  echo "$1" | perl -0777pe 's|([0-9a-zA-Z]{2}+(?![^\(]*\)))|\\x${1}|gs'
}

hex_patch() {
  local dom=$(hex "$2")
  local sub=$(hex "$3")
  perl -0777pi -e 'BEGIN{$/=\1e8} s|'"$dom"'|'"$sub"'|gs' "$1"
}

prep() {
  xattr -r -d com.apple.quarantine "$1"
  codesign --force --deep --sign - "$1"
}

patch_app() {
  for ((i = 0; i < ${#HEX_VALUES_APP[@]}; i += 2)); do
    hex_patch "$APP_FILE" "${HEX_VALUES_APP[i]}" "${HEX_VALUES_APP[i + 1]}"
  done
}

patch_lib() {
  hex_patch "$LIB_FILE" "${HEX_VALUES_LIB[@]:0:2}" "${HEX_VALUES_LIB[@]:2:2}"
}

# Main execution
check_utilities
patch_app
patch_lib
prep "$APP_PATH"
