#!/bin/bash
host="2600:1700:28b0:e021::84f"
year=2022
for f in "$@"; do
	if [ -d "$f/Captions" ]; then
		srcpath="$(realpath "$f")"
		week="$(basename "$f")"
		rsync -Pa -e ssh "$srcpath/Captions" "$srcpath/CSV" "$srcpath/logs" "$srcpath/thumbs" "$srcpath/"*.txt "$srcpath/"*.xlsx "$srcpath/"*.prproj "pijn@[2600:1700:28b0:e021::84f]:/home/pijn/PIJN/Storage/$year/$week/"
	fi
done
